from usb.device.keyboard import KeyCode

hid_keymap = {
    # Betűk, írásjelek
    "A": KeyCode.A,
    "B": KeyCode.B,
    "C": KeyCode.C,
    "D": KeyCode.D,
    "E": KeyCode.E,
    "F": KeyCode.F,
    "G": KeyCode.G,
    "H": KeyCode.H,
    "I": KeyCode.I,
    "J": KeyCode.J,
    "K": KeyCode.K,
    "L": KeyCode.L,
    "M": KeyCode.M,
    "N": KeyCode.N,
    "O": KeyCode.O,
    "P": KeyCode.P,
    "Q": KeyCode.Q,
    "R": KeyCode.R,
    "S": KeyCode.S,
    "T": KeyCode.T,
    "U": KeyCode.U,
    "V": KeyCode.V,
    "W": KeyCode.W,
    "X": KeyCode.X,
    "Y": KeyCode.Y,
    "Z": KeyCode.Z,
    "Ö": KeyCode.N0,
    "Ü": KeyCode.MINUS,
    "Ó": KeyCode.EQUAL,
    "Ő": KeyCode.OPEN_BRACKET,
    "Ú": KeyCode.CLOSE_BRACKET,
    "É": KeyCode.SEMICOLON,
    "Á": KeyCode.QUOTE,
    "Ű": KeyCode.BACKSLASH,
    "Í": 0x64,
    ",": KeyCode.COMMA,
    ".": KeyCode.DOT,
    "-": KeyCode.SLASH,

    # Felső számsor
    "1": KeyCode.N1,
    "2": KeyCode.N2,
    "3": KeyCode.N3,
    "4": KeyCode.N4,
    "5": KeyCode.N5,
    "6": KeyCode.N6,
    "7": KeyCode.N7,
    "8": KeyCode.N8,
    "9": KeyCode.N9,
    "0": KeyCode.GRAVE,

    # Alap billentyűk
    "ESC": KeyCode.ESCAPE,
    "ENTER": KeyCode.ENTER,
    "BACKSPACE": KeyCode.BACKSPACE,
    "TAB": KeyCode.TAB,
    "SPACE": KeyCode.SPACE,
    "CAPSLOCK": KeyCode.CAPS_LOCK,
    "DEL": KeyCode.DELETE,
    "INS": KeyCode.INSERT,

    # Funkcióbillentyűk
    "F1": KeyCode.F1,
    "F2": KeyCode.F2,
    "F3": KeyCode.F3,
    "F4": KeyCode.F4,
    "F5": KeyCode.F5,
    "F6": KeyCode.F6,
    "F7": KeyCode.F7,
    "F8": KeyCode.F8,
    "F9": KeyCode.F9,
    "F10": KeyCode.F10,
    "F11": KeyCode.F11,
    "F12": KeyCode.F12,

    "PRTSC": KeyCode.PRINTSCREEN,
    "PAUSE": KeyCode.PAUSE,

    # Navigáció
    "HOME": KeyCode.HOME,
    "PGUP": KeyCode.PAGEUP,
    "END": KeyCode.END,
    "PGDN": KeyCode.PAGEDOWN,
    "UP": KeyCode.UP,
    "DOWN": KeyCode.DOWN,
    "LEFT": KeyCode.LEFT,
    "RIGHT": KeyCode.RIGHT,

    # Numerikus billentyűzet
    "NUMLOCK": KeyCode.KP_NUM_LOCK,
    "NUM/": KeyCode.KP_DIVIDE,
    "NUM*": KeyCode.KP_MULTIPLY,
    "NUM-": KeyCode.KP_MINUS,
    "NUM+": KeyCode.KP_PLUS,
    "NUMENTER": KeyCode.KP_ENTER,
    "NUM1": KeyCode.KP_1,
    "NUM2": KeyCode.KP_2,
    "NUM3": KeyCode.KP_3,
    "NUM4": KeyCode.KP_4,
    "NUM5": KeyCode.KP_5,
    "NUM6": KeyCode.KP_6,
    "NUM7": KeyCode.KP_7,
    "NUM8": KeyCode.KP_8,
    "NUM9": KeyCode.KP_9,
    "NUM0": KeyCode.KP_0,
    "NUM.": 0x63,

    # Módosítók
    "LCTRL": KeyCode.LEFT_CTRL,
    "LSHIFT": KeyCode.LEFT_SHIFT,
    "LALT": KeyCode.LEFT_ALT,
    "WIN": KeyCode.LEFT_UI,
    "RCTRL": KeyCode.RIGHT_CTRL,
    "RSHIFT": KeyCode.RIGHT_SHIFT,
    "ALTGR": KeyCode.RIGHT_ALT,
    "MENU": 0x65,
}





